### PR TITLE
Resolve first build error

### PR DESCRIPTION
**Pull request by Zcool85**
Resolve first build error

### CODE REVIEW

**Comment by jawher** [comment]
Hi @Zcool85 and thanks for this great PR !

Could you please squash the 2 commits and get rid of the debug `echo` in the Makefile ?

Looking forward to merging this.

**Comment by Zcool85** [comment]
Hi @jawher,

All is done !

**Comment by jawher** [comment]
Merci infiniment @Zcool85 pour cette superbe contribution :+1:

**Comment by Zcool85** [comment]
De rien :)

**Pull request merged**
